# Github actions workflow file to build and deploy the MunsonPickles.Api project

name: Build and Deploy MunsonPickles.Api

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main "]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Build with dotnet
        run: dotnet build MunsonPickles.Api/MunsonPickles.Api.csproj --configuration Release
      #- name: Publish to Azure Web App
      #  uses: azure/webapps-deploy@v2
      #  with:
      #    app-name: "munsonpickles-api"
      #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #    package: ./MunsonPickles.Api/bin/Release/net5.0/publish
